// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDshCS_G2eNSMhCXpbzcq4BW_bOdHxvIAg',
    appId: '1:244212724590:web:cd39d2d76a5cbc8336477f',
    messagingSenderId: '244212724590',
    projectId: 'feel-care-2e521',
    authDomain: 'feel-care-2e521.firebaseapp.com',
    storageBucket: 'feel-care-2e521.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe-QWqliLVf5Hdoekr1GTxuoBVfAumclY',
    appId: '1:244212724590:android:7b2600c0190ea8c436477f',
    messagingSenderId: '244212724590',
    projectId: 'feel-care-2e521',
    storageBucket: 'feel-care-2e521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpgpKT79IA37v70cX8YbX5MslwWUJseOo',
    appId: '1:244212724590:ios:49bd9c1519c20ced36477f',
    messagingSenderId: '244212724590',
    projectId: 'feel-care-2e521',
    storageBucket: 'feel-care-2e521.firebasestorage.app',
    iosBundleId: 'com.example.feelcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpgpKT79IA37v70cX8YbX5MslwWUJseOo',
    appId: '1:244212724590:ios:49bd9c1519c20ced36477f',
    messagingSenderId: '244212724590',
    projectId: 'feel-care-2e521',
    storageBucket: 'feel-care-2e521.firebasestorage.app',
    iosBundleId: 'com.example.feelcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDshCS_G2eNSMhCXpbzcq4BW_bOdHxvIAg',
    appId: '1:244212724590:web:3905d3d3ad1fb1d136477f',
    messagingSenderId: '244212724590',
    projectId: 'feel-care-2e521',
    authDomain: 'feel-care-2e521.firebaseapp.com',
    storageBucket: 'feel-care-2e521.firebasestorage.app',
  );
}
